# Generated by Django 5.0.7 on 2024-07-20 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_rename_user_users"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="password",
            new_name="密码",
        ),
        migrations.RenameField(
            model_name="users",
            old_name="username",
            new_name="用户名",
        ),
    ]
