# Generated by Django 5.0.7 on 2024-07-20 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_rename_password_users_密码_rename_username_users_用户名"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="密码",
            new_name="password",
        ),
        migrations.RenameField(
            model_name="users",
            old_name="用户名",
            new_name="username",
        ),
    ]
