# Generated by Django 5.0.7 on 2024-07-20 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_rename_密码_users_password_rename_用户名_users_username"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Users",
            new_name="User",
        ),
    ]
