# Generated by Django 5.0.7 on 2024-07-30 03:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_alter_project_user_alter_eval_result_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="modify_time",
            field=models.DateTimeField(auto_now=True, verbose_name="修改时间"),
        ),
    ]
